---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1beta2.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./pvc.yaml
  - ./filebrowser/ks.yaml
  # - ./kavita/ks.yaml
components:
  - ../../../flux/components/alerts
  - ../../../flux/components/namespace
