---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kubelet-csr-approver
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  path: ./kubernetes/service/core/kube-system/kubelet-csr-approver/app
  prune: false # never should be deleted
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: kube-system
  timeout: 5m
  wait: false
