---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app emqx
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cert-manager
  interval: 30m
  path: ./kubernetes/service/apps/emqx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: emqx
  timeout: 5m
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app emqx-cluster
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: emqx
    - name: onepassword-store
    - name: external-cloudflare-access-groups
  interval: 30m
  path: ./kubernetes/service/apps/emqx/cluster
  postBuild:
    substitute:
      APP: emqx
      CLOUDFLARE_SUBDOMAIN: pub-sub
      CLOUDFLARE_ZEROTRUST_ACCESS_GROUP_NAME: oidc-admin
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: emqx
  timeout: 5m
  wait: true
