---
formatter:
  type: basic
  include_document_start: true
  retain_line_breaks: true
  retain_line_breaks_single: true
  scan_folded_as_literal: true
  drop_merge_tag: true
  trim_trailing_whitespace: true
  eof_newline: true
