---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-zero-trust-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudflare-zero-trust-operator
      version: 0.7.1
      sourceRef:
        kind: HelmRepository
        name: zelic
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    secretRef: cloudflare-zero-trust-operator-secret
    podAnnotations:
      reloader.stakater.com/auto: "true"
