---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app filebrowser
  namespace: &namespace media
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../../flux/components/cloudflare/zero-trust
    - ../../../../../flux/components/gatus/external
  dependsOn:
    - name: openebs
    - name: external-cloudflare-access-groups
  interval: 30m
  path: ./kubernetes/service/apps/media/filebrowser/app
  postBuild:
    substitute:
      APP: *app
      CLOUDFLARE_SUBDOMAIN: &subdomain files
      GATUS_SUBDOMAIN: *subdomain
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
