---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gatus
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: openebs
    - name: onepassword-store
    - name: external-cloudflare-access-groups
  interval: 30m
  path: ./kubernetes/service/core/observability/gatus/app
  postBuild:
    substitute:
      APP: *app
      CLOUDFLARE_SUBDOMAIN: &subdomain status
      GATUS_SUBDOMAIN: *subdomain
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: observability
  timeout: 5m
  wait: false
