---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gatus
  namespace: &namespace observability
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../../flux/components/cloudflare/zero-trust
  dependsOn:
    - name: openebs
      namespace: openebs-system
    - name: onepassword-store
      namespace: secrets
    - name: external-cloudflare-access-groups
      namespace: network
  interval: 30m
  path: ./kubernetes/service/core/observability/gatus/app
  postBuild:
    substitute:
      APP: *app
      CLOUDFLARE_SUBDOMAIN: status
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
