---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kube-prometheus-stack
  namespace: &namespace observability
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: openebs
      namespace: openebs-system
    - name: onepassword-store
      namespace: secrets
    - name: kube-prometheus-stack-crds
      namespace: observability
  interval: 30m
  path: ./kubernetes/service/core/observability/kube-prometheus-stack/app
  postBuild:
    substitute:
      APP: *app
      CLOUDFLARE_ALERTMANAGER_SUBDOMAIN: alerts
      CLOUDFLARE_PROMETHEUS_SUBDOMAIN: metrics
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kube-prometheus-stack-crds
  namespace: &namespace observability
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  path: ./kubernetes/service/core/observability/kube-prometheus-stack/crds
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kube-prometheus-stack-prometheus-access
  namespace: &namespace observability
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: kube-prometheus-stack
      namespace: observability
    - name: external-cloudflare-access-groups
      namespace: network
  interval: 30m
  path: ./kubernetes/service/core/observability/kube-prometheus-stack/access
  postBuild:
    substitute:
      APP: prometheus
      CLOUDFLARE_SUBDOMAIN: &subdomain metrics
      CLOUDFLARE_ZEROTRUST_ACCESS_GROUP_NAME: oidc-admin
      GATUS_SUBDOMAIN: *subdomain
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kube-prometheus-stack-alertmanager-access
  namespace: &namespace observability
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: kube-prometheus-stack
      namespace: observability
    - name: external-cloudflare-access-groups
      namespace: network
  interval: 30m
  path: ./kubernetes/service/core/observability/kube-prometheus-stack/access
  postBuild:
    substitute:
      APP: alertmanager
      CLOUDFLARE_SUBDOMAIN: &subdomain alerts
      CLOUDFLARE_ZEROTRUST_ACCESS_GROUP_NAME: oidc-admin
      GATUS_SUBDOMAIN: *subdomain
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
