---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app external-ingress-nginx
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cert-manager-tls
    - name: onepassword-store
    - name: external-cloudflare-tunnel
  interval: 30m
  path: ./kubernetes/service/core/network/external/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: network
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app external-external-dns
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: onepassword-store
  interval: 30m
  path: ./kubernetes/service/core/network/external/external-dns
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: network
  timeout: 5m
  wait: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app external-cloudflare-tunnel
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-external-dns
    - name: onepassword-store
  interval: 30m
  path: ./kubernetes/service/core/network/external/cloudflare-tunnel
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: network
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app external-cloudflare-zero-trust-operator
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: onepassword-store
  interval: 30m
  path: ./kubernetes/service/core/network/external/cloudflare-zero-trust/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: network
  timeout: 5m
  wait: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app external-cloudflare-access-tokens
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-cloudflare-zero-trust-operator
  interval: 30m
  path: ./kubernetes/service/core/network/external/cloudflare-zero-trust/access/tokens
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: network
  timeout: 5m
  wait: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app external-cloudflare-access-groups
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-cloudflare-access-tokens
  interval: 30m
  path: ./kubernetes/service/core/network/external/cloudflare-zero-trust/access/groups
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: network
  timeout: 5m
  wait: true
