---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./pvc.yaml
configMapGenerator:
  - name: authelia-configmap
    files:
      - configuration.yaml=./resources/configuration.yaml
      - litestream.yml=./resources/litestream.yml
generatorOptions:
  disableNameSuffixHash: true
