---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capacitor
spec:
  interval: 30m
  chart:
    spec:
      chart: capacitor
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: sebastiangaiser
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    capacitor:
      readonly: false
    ingress:
      enabled: true
      className: "external"
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${CLOUDFLARE_DOMAIN}"
      hosts:
        - host: "${CLOUDFLARE_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
