---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.6.0/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: blocky
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        name: bjw-s
        kind: HelmRepository
        namespace: flux-system
  values:
    controllers:
      blocky:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/0xerr0r/blocky
              tag: v0.24@sha256:9a82e0235c52ef3048586f8006add06e52132adaae70d02f980569dae16421a2
            env:
              TZ: "${CLUSTER_TZ}"
            securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
                add: ["NET_BIND_SERVICE"]
            resources:
              requests:
                cpu: 50m
                memory: 32Mi
              limits:
                cpu: 500m
                memory: 128Mi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  exec:
                    command: ["/app/blocky", "healthcheck", "--port", "8053"]
                  initialDelaySeconds: 10
                  timeoutSeconds: 5
                  periodSeconds: 10
                  failureThreshold: 10
              readiness: *probes
    service:
      blocky:
        controller: blocky
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: "192.168.2.81"
        ports:
          http:
            port: 8080
            protocol: HTTP
          dns:
            port: &dns_port 53
            targetPort: &dns_target_port 8053
            protocol: UDP
            appProtocol: dns
          dns-tcp:
            port: *dns_port
            targetPort: *dns_target_port
            protocol: TCP
            appProtocol: dns
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: &uid 1000
        runAsGroup: *uid
        fsGroup: *uid
        fsGroupChangePolicy: "OnRootMismatch"
        seccompProfile: { type: RuntimeDefault }
    persistence:
      config:
        type: configMap
        name: blocky-config
        advancedMounts:
          blocky:
            main:
              - path: /app/config.yml
                subPath: config.yaml
                readOnly: true
      # secrets:
      #   type: secret
      #   name: blocky-secrets
      #   defaultMode: 0400
      #   advancedMounts:
      #     blocky:
      #       main:
      #         - subPath: allowlist
      #           path: /secrets/allowlist
      #         - subPath: blocklist
      #           path: /secrets/blocklist
    serviceMonitor:
      blocky:
        serviceName: blocky
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 30s
