---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app headlamp
  namespace: &namespace flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../../flux/components/cloudflare/zero-trust
    - ../../../../../flux/components/gatus/external
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  interval: 30m
  path: ./kubernetes/service/core/flux-system/headlamp/app
  postBuild:
    substitute:
      APP: *app
      CLOUDFLARE_SUBDOMAIN: &subdomain gitops
      GATUS_SUBDOMAIN: *subdomain
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
