---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../../flux/components/gatus/external
  - ../../../../../flux/components/cloudflare/zero-trust
