---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: &name gatus-service-token
spec:
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: *name
  template:
    engineVersion: v2
    data:
      cloudflareClientId: '{{.cloudflareClientId}}'
      cloudflareSecretKey: '{{.cloudflareSecretKey}}'
      serviceTokenID: '{{.serviceTokenID}}'
  data:
    - match:
        secretKey: &key cloudflareClientId
        remoteRef:
          remoteKey: *name
          property: *key
    - match:
        secretKey: &key cloudflareSecretKey
        remoteRef:
          remoteKey: *name
          property: *key
    - match:
        secretKey: &key serviceTokenID
        remoteRef:
          remoteKey: *name
          property: *key
