---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
spec:
  interval: 30m
  chart:
    spec:
      chart: headlamp
      version: 0.28.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    podAnnotations:
      reloader.stakater.com/auto: "true"
    fullnameOverride: headlamp
    initContainers:
      - name: headlamp-plugins
        image: iotops/headlamp-plugin-flux:latest@sha256:bcfbfe6257c3367669847ada2017ebac593004afbd9e92c9ce5796675920ef2e
        command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins
    config:
      oidc:
        secret:
          create: false
      pluginsDir: /build/plugins
    ingress:
      enabled: true
      ingressClassName: external
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${CLOUDFLARE_DOMAIN}"
      hosts:
        - host: "${CLOUDFLARE_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}"
          paths:
            - path: /
              type: Prefix
    persistentVolumeClaim:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi
      storageClassName: openebs-zfs-shared
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
    volumes:
      - name: headlamp-plugins
        persistentVolumeClaim:
          claimName: headlamp
